#!/usr/bin/env python
# (c) Copyright 2017-2018 OLX

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import os
import sys

repobase = os.path.split(os.path.realpath(sys.modules[__name__].__file__))[0]

sys.path.insert(0, os.path.join(repobase, 'lib'))

import python_path
import command_loader
import kube_loader

import command


def main():
    sys.exit(command.Command.run_command())

if __name__ == '__main__':
    main()
